"""
orchestrator.py
---------------
Advanced Modular Salesforce RAG chatbot pipeline.

Control flow:
  query ──► [Memory] ──► [Pre-Retrieval: Query Rewrite]
        ──► [Router] ──► [ChromaDB Retrieval]
        ──► [Post-Retrieval: Answer Grading]
        ──► Final Response ──► [Memory Update]
"""

from llm_client import generate_response
from router import router
from tools import retrieve_context


# ── Prompt Templates ───────────────────────────────────────────────────────────

QUERY_REWRITE_PROMPT = """
You are an expert Salesforce assistant helping to optimize search queries.

You will be given a conversation history and a new user query.
Your task is to rewrite the user's query into a clear, self-contained,
and search-optimized question that can be used to retrieve relevant 
Salesforce documentation.

Rules:
- Resolve ALL pronouns (e.g., "it", "that", "they") using the conversation history.
- Make the rewritten query specific and rich with Salesforce keywords.
- Return ONLY the rewritten query. No explanation, no quotes.

If the query is already clear, return it unchanged.
"""

SALESFORCE_PROMPT_TEMPLATE = """
You are an expert Salesforce assistant.

### CONTEXT (Retrieved from official Salesforce documentation):
{context}

### INSTRUCTIONS:
- Answer the user's question using ONLY the information in the CONTEXT above.
- If the context does not contain enough information to answer, say:
  "I don't have enough information in my knowledge base for this. Please consult the official Salesforce documentation."
- Do NOT make up facts. Be concise and precise.
- Format code snippets or steps using markdown if applicable.

### USER QUESTION:
{query}
"""

GENERAL_PROMPT_TEMPLATE = """
You are a specialized Salesforce Expert Chatbot. You do not answer general knowledge questions.

### INSTRUCTIONS:
1. If the user is just saying a basic greeting (e.g., "Hi", "Hello", "Good morning", "How are you?"), you MAY respond politely and introduce yourself as a Salesforce Expert.
2. If the user asks ANY question or topic that is NOT about Salesforce, you MUST reply with exactly:
   "I'm a Salesforce expert and I can't answer queries outside of that scope. If you want anything related to Salesforce, feel free to ask!"
3. Do NOT provide the answer to their general knowledge question, even if you know it.
4. Keep your response brief.

### USER QUESTION:
{query}
"""

GRADING_PROMPT = """
You are a lenient quality-control evaluator for a Salesforce RAG chatbot.

You will be given:
1. A user question.
2. The context retrieved from documentation.
3. A draft answer generated by the AI.

Your ONLY job is to catch CLEAR factual fabrications — invented API names, 
false method signatures, or completely wrong facts not even remotely supported 
by the context.

IMPORTANT:
- If the answer is a reasonable, honest answer to the question, reply "PASS".
- If the answer says it lacks information or asks user to consult docs, reply "PASS".
- If the answer adds extra explanation or examples beyond the context, reply "PASS".
- ONLY reply "FAIL" if the answer invents specific facts (e.g., method names, 
  class names, field values) that are clearly not in the context AND are wrong.

OUTPUT RULES:
- Reply with ONLY "PASS" or "FAIL". No explanation.
"""

FOLLOWUP_PROMPT_TEMPLATE = """
You are an expert Salesforce assistant continuing a conversation.

The user is asking a follow-up question about a response you already gave.
Use your previous answer (available in the conversation history) to answer this.

Do NOT say you don't know if you just explained this. Be helpful and expand
on your previous answer naturally.

### USER FOLLOW-UP:
{query}
"""


# ── Core Functions ─────────────────────────────────────────────────────────────

# Follow-up indicator phrases — signals user is asking about a previous response
_FOLLOWUP_SIGNALS = [
    "you wrote", "you said", "you mentioned", "the code you", "that code",
    "your answer", "your response", "you gave", "can you explain", "guide me",
    "explain that", "elaborate", "tell me more", "what do you mean", "go deeper",
    "expand on", "continue", "next step", "more detail", "in detail",
]


def _is_followup_on_bot_response(query: str, chat_history: list) -> bool:
    """Returns True if the user is asking about the bot's previous answer, not a new topic."""
    if not chat_history:
        return False
    q_lower = query.lower()
    return any(signal in q_lower for signal in _FOLLOWUP_SIGNALS)


def _rewrite_query(raw_query: str, chat_history: list) -> str:
    """Pre-Retrieval: Rewrites the raw user query using chat history for context."""
    if not chat_history:
        return raw_query
    rewritten = generate_response(raw_query, QUERY_REWRITE_PROMPT, chat_history)
    rewritten = rewritten.strip()
    # Safety: if rewrite is empty or suspiciously short, fall back to original
    if not rewritten or len(rewritten) < 5:
        return raw_query
    return rewritten


def _grade_answer(query: str, context: str, draft_answer: str) -> str:
    """Post-Retrieval: Grades the draft answer. Only fails on clear fabrications."""
    grading_user_msg = (
        f"USER QUESTION: {query}\n\n"
        f"CONTEXT:\n{context}\n\n"
        f"DRAFT ANSWER:\n{draft_answer}"
    )
    verdict = generate_response(grading_user_msg, GRADING_PROMPT).strip().upper()

    if "FAIL" in verdict and "PASS" not in verdict:
        return (
            "I found relevant information in my knowledge base, but I want to be "
            "careful not to give you incorrect details. Please consult the official "
            "Salesforce documentation at https://help.salesforce.com for a definitive answer."
        )
    return draft_answer


# ── Main Orchestrator ──────────────────────────────────────────────────────────

def orchestrate_query(query: str, chat_history: list) -> str:
    """
    Full Advanced RAG pipeline:
      Pre-Retrieval (Query Rewrite) → Route → Retrieve → Generate → Post-Retrieval (Grade).

    Args:
        query        : The raw user question.
        chat_history : Running list of {"role": ..., "content": ...} messages.

    Returns:
        The final, graded LLM response as a string.
    """

    # ── Step 0: Duplicate Detection ─────────────────────────────────────────────
    normalized_query = query.strip().lower().rstrip("?.")
    for msg in chat_history:
        if msg["role"] == "user":
            past_query = msg["content"].strip().lower().rstrip("?.")
            if normalized_query == past_query:
                return "I've already answered this question above — feel free to scroll up! Is there anything else I can help you with?"

    # ── Step 1: Follow-up Detection (skip DB, answer from memory) ───────────────
    # If user is asking about something the bot just said, use chat history directly
    if _is_followup_on_bot_response(query, chat_history):
        followup_prompt = FOLLOWUP_PROMPT_TEMPLATE.format(query=query)
        return generate_response(query, followup_prompt, chat_history)

    # ── Step 2: Pre-Retrieval — Rewrite query using history ─────────────────────
    optimized_query = _rewrite_query(query, chat_history)

    # ── Step 3: Route the optimized query ───────────────────────────────────────
    module_name = router(optimized_query)

    # ── Step 4: Retrieve context from ChromaDB ───────────────────────────────────
    context = retrieve_context(optimized_query, module_name)
    has_context = bool(context.strip())

    # ── Step 5: Build prompt ─────────────────────────────────────────────────────
    if module_name == "general_queries":
        prompt = GENERAL_PROMPT_TEMPLATE.format(query=query)
    else:
        prompt = SALESFORCE_PROMPT_TEMPLATE.format(
            context=context if has_context else "No relevant context was found.",
            query=optimized_query,   # BUG FIX: use optimized query in prompt, not raw
        )

    # ── Step 6: Generate draft answer ────────────────────────────────────────────
    draft_answer = generate_response(optimized_query, prompt, chat_history)

    # ── Step 7: Post-Retrieval — Grade (only when we have real DB context) ───────
    if module_name != "general_queries" and has_context:
        final_answer = _grade_answer(optimized_query, context, draft_answer)
    else:
        final_answer = draft_answer

    return final_answer


# ── Interactive CLI ────────────────────────────────────────────────────────────

if __name__ == "__main__":
    print("=" * 60)
    print("  Salesforce Expert Chatbot  |  Type 'e' to exit")
    print("=" * 60)

    # A single session-level memory list
    chat_history = []

    while True:
        user_input = input("\nYou: ").strip()

        if user_input.lower() == 'e':
            print("Goodbye!")
            break

        if not user_input:
            continue

        answer = orchestrate_query(user_input, chat_history)

        # Update chat history with the latest exchange
        chat_history.append({"role": "user",      "content": user_input})
        chat_history.append({"role": "assistant",  "content": answer})

        print(f"\n🤖 Assistant:\n{answer}")
